require 'rubygems'
require 'gruff'

module Gruff
  autoload :AbstractSar, 'lib/gruff/sar/abstract_sar'
  autoload :IostatCount, 'lib/gruff/iostat'
  autoload :IostatByte, 'lib/gruff/iostat'
  autoload :IostatWait, 'lib/gruff/iostat'
  autoload :IostatBusy, 'lib/gruff/iostat'
  autoload :IostatMultiDevice, 'lib/gruff/iostat'
  autoload :SarR, 'lib/gruff/sar/sar_r'
  autoload :SarW1, 'lib/gruff/sar/sar_w'
  autoload :SarW2, 'lib/gruff/sar/sar_w'
  autoload :SarW3, 'lib/gruff/sar/sar_w'
  autoload :SarA, 'lib/gruff/sar/sar_a'
  autoload :SarQ1, 'lib/gruff/sar/sar_q'
  autoload :SarQ2, 'lib/gruff/sar/sar_q'
  autoload :SarU, 'lib/gruff/sar/sar_u'
  autoload :Vmstat, 'lib/gruff/vmstat'
  autoload :VmstatFreeMemory, 'lib/gruff/vmstat'
  autoload :VmstatPage1, 'lib/gruff/vmstat'
  autoload :VmstatPage2, 'lib/gruff/vmstat'
  autoload :VmstatCpu, 'lib/gruff/vmstat'
  autoload :NicstatByte, 'lib/gruff/nicstat'
  autoload :NicstatPacket, 'lib/gruff/nicstat'
  autoload :NicstatUsage, 'lib/gruff/nicstat'
end

